# Generated by Django 5.0 on 2023-12-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_cinemahall_overview_movie_duration_movie_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesession',
            name='bought_places',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
